version: "2"

run:
  timeout: 10m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gocyclo
    - misspell

settings:
  gocyclo:
    min-complexity: 15

issues:
  exclude-dirs:
    - testdata