version: 2

run:
  timeout: 10m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gocyclo
    - misspell

linters-settings:
  gocyclo:
    min-complexity: 15

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
    - path: testdata/
      linters:
        - errcheck
        - govet
        - staticcheck