version: "2"

run:
  timeout: 10m

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gocyclo
    - misspell

linters-settings:
  gocyclo:
    min-complexity: 15

issues:
  exclude-rules:
    - path: testdata
      linters:
        - gosec