run:
  timeout: 10m
  issues-exit-code: 1
  tests: true
  modules-download-mode: readonly

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: true
  sort-results: true

linters:
  disable-all: true
  enable:
    # Enabled by default linters
    - errcheck    # Check for unchecked errors
    - gosimple    # Simplify code
    - govet       # Standard go vet
    - ineffassign # Detect ineffectual assignments
    - staticcheck # Advanced static analysis
    - typecheck   # Type checking
    - unused      # Check for unused constants, variables, functions and types
    
    # Additional recommended linters for analysis tools
    - bodyclose     # Check whether HTTP response body is closed successfully
    - contextcheck  # Check the function whether use a non-inherited context
    - cyclop        # Check cyclomatic complexity
    - dupl          # Code clone detection
    - durationcheck # Check for two durations multiplied together
    - errorlint     # errorlint is a linter for that can be used to find code that will cause problems with the error wrapping
    - exhaustive    # Check exhaustiveness of enum switch statements
    - exportloopref # Check for pointers to enclosing loop variables
    - forbidigo     # Forbid identifiers
    - funlen        # Tool for detection of long functions
    - gochecknoglobals # Check that no global variables exist
    - gochecknoinits   # Check that no init functions are present
    - gocognit      # Compute and checks the cognitive complexity of functions
    - goconst       # Find repeated strings that could be replaced by a constant
    - gocritic      # Provides diagnostics that check for bugs, performance and style issues
    - gocyclo       # Compute and check the cyclomatic complexity of functions
    - godot         # Check if comments end in a period
    - goimports     # Check import formatting
    - gomnd         # Detect magic numbers
    - gomoddirectives # Manage the use of 'replace', 'retract', and 'excludes' directives in go.mod
    - gomodguard    # Allow and block list linter for direct Go module dependencies
    - goprintffuncname # Check that printf-like functions are named with f at the end
    - gosec         # Security audit
    - lll           # Report long lines
    - makezero      # Find slice declarations with non-zero initial length
    - misspell      # Find commonly misspelled English words in comments
    - nakedret      # Find naked returns in functions greater than a specified function length
    - nestif        # Report deeply nested if statements
    - nilerr        # Find the code that returns nil even if it checks that the error is not nil
    - nlreturn      # Check for a new line before return and branch statements
    - nolintlint    # Report ill-formed or insufficient nolint directives
    - predeclared   # Find code that shadows one of Go's predeclared identifiers
    - revive        # Fast, configurable, extensible, flexible, and beautiful linter for Go
    - rowserrcheck  # Check whether Err of rows is checked successfully
    - sqlclosecheck # Check that sql.Rows and sql.Stmt are closed
    - tparallel     # Detect inappropriate usage of t.Parallel() method in your Go test codes
    - unconvert     # Remove unnecessary type conversions
    - unparam       # Report unused function parameters
    - whitespace    # Detection of leading and trailing whitespace
    - wsl           # Whitespace Linter

linters-settings:
  cyclop:
    max-complexity: 15
    
  dupl:
    threshold: 150
    
  funlen:
    lines: 100
    statements: 50
    
  gocognit:
    min-complexity: 15
    
  gocyclo:
    min-complexity: 15
    
  goconst:
    min-len: 3
    min-occurrences: 3
    ignore-tests: true
    
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport # https://github.com/go-critic/go-critic/issues/845
      - ifElseChain
      - octalLiteral
      - whyNoLint
      
  gomnd:
    settings:
      mnd:
        checks:
          - argument
          - case
          - condition
          - operation
          - return
        ignored-numbers: 0,1,2,3
        ignored-functions: strings.SplitN
        
  gosec:
    excludes:
      - G204 # Subprocess launched with variable
      
  lll:
    line-length: 140
    
  misspell:
    locale: US
    ignore-words:
      - gcpclosecheck
      - testdata
      - analysistest
      - spanner
      - pubsub
      
  nakedret:
    max-func-lines: 30
    
  nestif:
    min-complexity: 4
    
  nlreturn:
    block-size: 3
    
  revive:
    min-confidence: 0
    rules:
      - name: atomic
      - name: line-length-limit
        arguments: [140]
      - name: argument-limit
        arguments: [5]
      - name: cyclomatic
        arguments: [15]
      - name: max-public-structs
        arguments: [5]
      - name: file-header
        disabled: true

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - funlen
        - gochecknoglobals
        - gochecknoinits
        - gomnd
        - lll
        
    # Exclude testdata files
    - path: testdata/
      linters:
        - errcheck
        - gosec
        - goconst
        - gomnd
        - unparam
        
    # Allow long lines in generated files
    - path: ".*\\.pb\\.go"
      linters:
        - lll
        
    # Specific excludes for analyzer code
    - text: "should have a package comment"
      linters:
        - revive
        
    # Allow TODO comments in development
    - source: "TODO|FIXME"
      linters:
        - godot
        
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  
severity:
  default-severity: error
  case-sensitive: false