version: "2"

run:
  timeout: 10m

linters:
  # v2 では disable-all の代わりに default を使う
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gocyclo
    - misspell
    - gosec

  # v2 では linters-settings → linters.settings に変更
  settings:
    gocyclo:
      min-complexity: 15

  # v2 では issues.exclude-rules → linters.exclusions.rules
  exclusions:
    rules:
      # testdata 配下は gosec を除外
      - path: ^testdata/
        linters:
          - gosec
      # すべての階層の *_test.go を gosec から除外
      - path: ".*_test\\.go$"
        linters:
          - gosec
          - gocyclo

      