linters-settings:
  cyclop:
    max-complexity: 15

run:
  timeout: 10m
  tests: true

linters:
  enable:
    - cyclop
    - gocyclo

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - cyclop