# golangci-lint configuration for gcpclosecheck
run:
  timeout: 5m
  tests: true
  skip-dirs:
    - testdata
  skip-files:
    - ".*\\.pb\\.go$"
    - ".*_generated\\.go$"

linters:
  enable:
    # Code quality
    - gofmt
    - goimports
    - govet
    - golint
    - ineffassign
    - misspell
    - errcheck
    - staticcheck
    - unused
    - deadcode
    - varcheck
    - structcheck
    - typecheck
    
    # Performance & Memory
    - prealloc
    - maligned
    
    # Security
    - gosec
    - gas
    
    # Style
    - gocyclo
    - gofumpt
    - whitespace
    - wsl
    
    # Complexity
    - funlen
    - gocognit
    - cyclop
    - nestif
    
    # Best practices
    - gocritic
    - godox
    - gomnd
    - goconst
    - unconvert
    
  disable:
    - scopelint # deprecated
    - interfacer # deprecated

linters-settings:
  gocyclo:
    min-complexity: 10
    
  funlen:
    lines: 80
    statements: 50
    
  gocognit:
    min-complexity: 15
    
  cyclop:
    max-complexity: 10
    package-average: 5.0
    skip-tests: true
    
  nestif:
    min-complexity: 4
    
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
      - experimental
      - opinionated
    disabled-checks:
      - commentedOutCode
      - whyNoLint
      
  govet:
    enable:
      - assign
      - atomic
      - bools
      - buildtag
      - cgocall
      - composites
      - copylocks
      - deepequalerrors
      - errorsas
      - httpresponse
      - loopclosure
      - lostcancel
      - nilfunc
      - nilness
      - printf
      - shift
      - stdmethods
      - structtag
      - tests
      - unmarshal
      - unreachable
      - unsafeptr
      - unusedresult
      
  maligned:
    suggest-new: true
    
  prealloc:
    simple: true
    range-loops: true
    for-loops: true
    
  gosec:
    includes:
      - G101 # Look for hard coded credentials
      - G102 # Bind to all interfaces
      - G103 # Audit the use of unsafe block
      - G104 # Audit errors not checked
      - G106 # Audit the use of ssh.InsecureIgnoreHostKey
      - G107 # Url provided to HTTP request as taint input
      - G108 # Profiling endpoint automatically exposed on /debug/pprof
      - G109 # Potential Integer overflow made by strconv.Atoi result conversion to int16/32
      - G110 # Potential DoS vulnerability via decompression bomb
      - G201 # SQL query construction using format string
      - G202 # SQL query construction using string concatenation
      - G203 # Use of unescaped data in HTML templates
      - G204 # Audit use of command execution
      - G301 # Poor file permissions used when creating a directory
      - G302 # Poor file permissions used with chmod
      - G303 # Creating tempfile using a predictable path
      - G304 # File path provided as taint input
      - G305 # File traversal when extracting zip/tar archive
      - G306 # Poor file permissions used when writing to a new file
      - G307 # Deferring a method which returns an error
      - G401 # Detect the usage of DES, RC4, MD5 or SHA1
      - G402 # Look for bad TLS connection settings
      - G403 # Ensure minimum RSA key length of 2048 bits
      - G404 # Insecure random number source (rand)
      - G501 # Import blocklist: crypto/md5
      - G502 # Import blocklist: crypto/des
      - G503 # Import blocklist: crypto/rc4
      - G504 # Import blocklist: net/http/cgi
      - G505 # Import blocklist: crypto/sha1
      - G601 # Implicit memory aliasing of items from a range statement
      
  gomnd:
    settings:
      mnd:
        checks: 
          - argument
          - case
          - condition
          - operation
          - return
          - assign
        ignored-numbers: 0,1,2,3
        ignored-files: 
          - ".*_test.go"
        ignored-functions: 
          - "strings.SplitN"
          - "bytes.SplitN"

issues:
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - funlen
        - gomnd
        
    # Exclude testdata from all checks
    - path: testdata/
      linters:
        - all
        
    # Exclude generated files
    - path: ".*\\.pb\\.go"
      linters:
        - all
        
  exclude:
    # Allow unhandled errors in defer statements for Close methods
    - 'Error return value of `.*\.Close` is not checked'
    
    # Allow magic numbers in test files
    - 'Magic number: \d+, in <test> file'

  max-issues-per-linter: 0
  max-same-issues: 0

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: true
  sort-results: true