services:
    - service_name: spanner
      package_path: cloud.google.com/go/spanner
      creation_functions:
        - NewClient
        - NewClientWithConfig
        - ReadOnlyTransaction
        - ReadWriteTransaction
        - BatchReadOnlyTransaction
        - Query
        - Read
      cleanup_methods:
        - method: Close
          required: true
          description: Spannerクライアント接続のクローズ
        - method: Stop
          required: true
          description: RowIteratorの停止
    - service_name: storage
      package_path: cloud.google.com/go/storage
      creation_functions:
        - NewClient
        - NewReader
        - NewWriter
        - NewComposer
      cleanup_methods:
        - method: Close
          required: true
          description: ストレージクライアント/ストリーム接続のクローズ
    - service_name: pubsub
      package_path: cloud.google.com/go/pubsub
      creation_functions:
        - NewClient
        - NewClientWithConfig
        - Receive
        - NewMessage
      cleanup_methods:
        - method: Close
          required: true
          description: Pub/Subクライアント接続のクローズ
        - method: Stop
          required: true
          description: サブスクリプション受信の停止
        - method: Shutdown
          required: true
          description: メッセージ処理の終了
    - service_name: vision
      package_path: cloud.google.com/go/vision/apiv1
      creation_functions:
        - NewImageAnnotatorClient
        - NewProductSearchClient
      cleanup_methods:
        - method: Close
          required: true
          description: Vision APIクライアント接続のクローズ
    - service_name: admin
      package_path: cloud.google.com/go/iam/admin/apiv1
      creation_functions:
        - NewIamClient
      cleanup_methods:
        - method: Close
          required: true
          description: IAM Adminクライアント接続のクローズ
    - service_name: recaptcha
      package_path: cloud.google.com/go/recaptchaenterprise/apiv1
      creation_functions:
        - NewRecaptchaEnterpriseServiceClient
      cleanup_methods:
        - method: Close
          required: true
          description: reCAPTCHA Enterpriseクライアント接続のクローズ
    - service_name: bigquery
      package_path: cloud.google.com/go/bigquery
      creation_functions:
        - NewClient
        - NewJob
      cleanup_methods:
        - method: Close
          required: true
          description: BigQueryクライアント接続のクローズ
    - service_name: firestore
      package_path: cloud.google.com/go/firestore
      creation_functions:
        - NewClient
        - NewClientWithDatabase
      cleanup_methods:
        - method: Close
          required: true
          description: Firestoreクライアント接続のクローズ
    - service_name: functions
      package_path: cloud.google.com/go/functions/apiv1
      creation_functions:
        - NewCloudFunctionsServiceClient
      cleanup_methods:
        - method: Close
          required: true
          description: Cloud Functionsクライアント接続のクローズ
package_exceptions:
    - name: cmd_short_lived
      pattern: '*/cmd/*'
      condition:
        type: short_lived
        description: 短命プログラム例外
        enabled: true
    - name: cloud_functions
      pattern: '**/function/**'
      condition:
        type: cloud_function
        description: Cloud Functions例外
        enabled: true
    - name: test_files
      pattern: '**/*_test.go'
      condition:
        type: test
        description: テストコード例外
        enabled: false
